FROM debian:12.5-slim

# C
ENV GREEN="Bulbasaur"
RUN echo "'${BLUE}' | '${RED}' | '${GREEN}' | '${YELLOW}'"

# D
CMD export YELLOW="Pikachu" && \
    echo "'${BLUE}' | '${RED}' | '${GREEN}' | '${YELLOW}'"