FROM debian:12.5-slim


CMD echo "${BLUE-undefined}"
#
# ${<variable name>-<default value>}
#
# You can define default values.
# https://docs.docker.com/compose/environment-variables/variable-interpolation/#interpolation-syntax
